# Generated by Django 5.2.3 on 2025-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('serial', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('blood_group', models.CharField()),
                ('expiry_date', models.DateField()),
                ('NID_number', models.IntegerField()),
                ('emergency', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
