# Generated by Django 5.2.3 on 2025-06-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehandling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='serial',
        ),
    ]
