# Generated by Django 5.2.3 on 2025-06-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehandling', '0002_remove_employee_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='emp_id',
        ),
    ]
