# Generated by Django 5.2.3 on 2025-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandling', '0004_alter_employee_emergency_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='NID_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
