# Generated by Django 5.2.3 on 2025-07-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandling', '0005_alter_employee_nid_number_alter_employee_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excels/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
