# Generated by Django 5.2.3 on 2025-07-08 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandling', '0006_uploadedexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='excel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filehandling.uploadedexcel'),
        ),
    ]
