# Generated by Django 5.2.3 on 2025-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandling', '0014_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
